### PR TITLE
Add "What's New" site section built with Publish

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This is not published anywhere yet, but just a draft of what we could deploy on GitHub Pages as a section of our website.

I'm not sure if it should be deployed to `swiftwasm.org/whats-new` or maybe `swiftwasm.org/blog`? Maybe it should not be limited just to updates, but a general blog, potentially with guest posts etc, and monthly/biweekly updates could be just a part of it?

### CODE REVIEW

**Review by kateinoigakukun — APPROVED** [review]

**Review by carson-katri — APPROVED** [review]

**Comment by kateinoigakukun** [comment]
> I'm not sure if it should be deployed to swiftwasm.org/whats-new or maybe swiftwasm.org/blog? Maybe it should not be limited just to updates, but a general blog, potentially with guest posts etc, and monthly/biweekly updates could be just a part of it?


I prefer `blog` because it should not be limited to update 👍

**Review by j-f1 — APPROVED** [review]
Was going to ask for an RSS feed but Publish provides one by default 🙌

**Comment by MaxDesiatov** [comment]
Turns out Publish doesn't support deployments to subpaths, so `swiftwasm.org/blog` won't work as it breaks all links. I'm closing this in favor of the [`blog.swiftwasm.org`](https://github.com/swiftwasm/blog.swiftwasm.org) repository.

**Comment by carson-katri** [comment]
Is there an issue for this on Publish? If not we might want to make one or open a PR, I assume others would also want to put the site on a subpath...

**Comment by MaxDesiatov** [comment]
Unfortunately, Publish repository (as apparently most if not all Sundell's repositories) doesn't even allow creating issues. You can only submit a PR, and a lot of them just stay there not merged for long time. 😔

**Pull request closed without merging**
